export const Actions ={
    // INTERNET_CONNECTION:'INTERNET_CONNECTION',
    SET_USER_INFO:'SET_USER_INFO',
    SET_PLAYER_INFO : 'SET_PLAYER_INFO'
    // CART_LIST_REMOVE : 'CART_LIST_REMOVE',
    // SET_CURRENT_LOCATION:'SET_CURRENT_LOCATION'
}